set(_CATKIN_CURRENT_PACKAGE "ardronepkg")
set(ardronepkg_VERSION "0.0.0")
set(ardronepkg_MAINTAINER "lukas <lukas.nyboe.bek@gmail.com>")
set(ardronepkg_PACKAGE_FORMAT "1")
set(ardronepkg_BUILD_DEPENDS "ardrone_autonomy" "geographic_msgs" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "cv_bridge")
set(ardronepkg_BUILD_EXPORT_DEPENDS "ardrone_autonomy" "geographic_msgs" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "cv_bridge")
set(ardronepkg_BUILDTOOL_DEPENDS "catkin")
set(ardronepkg_BUILDTOOL_EXPORT_DEPENDS )
set(ardronepkg_EXEC_DEPENDS "ardrone_autonomy" "geographic_msgs" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "cv_bridge")
set(ardronepkg_RUN_DEPENDS "ardrone_autonomy" "geographic_msgs" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "cv_bridge")
set(ardronepkg_TEST_DEPENDS )
set(ardronepkg_DOC_DEPENDS )
set(ardronepkg_DEPRECATED "")